Repository openshift/hypershift-oadp-plugin, pull requests merged in 2025-06, with the labels that each got.

#74 Konflux: hermetic, multiarch, tags, labels, rpms
  .tekton/oadp-hypershift-oadp-plugin-oadp-1-5-pull-request.yaml
  .tekton/oadp-hypershift-oadp-plugin-oadp-1-5-push.yaml
  Dockerfile.oadp
  hack/build/redhat.repo
  hack/build/rpms.in.yaml
  hack/build/rpms.lock.yaml
Labels: tide/merge-method-squash, lgtm, approved

#81 NO-JIRA: Update fixes to OADP-1.5 branch from main
  examples/AWS/02-dpa-aws.yaml
  examples/BareMetal/02-dpa-bm.yaml
  examples/Openstack/02-dpa-osp.yaml
  examples/kubevirt/02-dpa-kubevirt.yaml
  go.mod
  go.sum
  main.go
  pkg/common/types.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/core/backup.go
  pkg/core/restore.go
  vendor/modules.txt
Labels: lgtm, jira/valid-reference, approved

#86 Red Hat Konflux update oadp-hypershift-oadp-plugin-oadp-1-5
  .tekton/oadp-hypershift-oadp-plugin-oadp-1-5-pull-request.yaml
  .tekton/oadp-hypershift-oadp-plugin-oadp-1-5-push.yaml
  Dockerfile.oadp
Labels: lgtm, approved
