Repository openshift/hypershift-oadp-plugin, pull requests merged in 2025-04, with the labels that each got.

#9 NO-JIRA: go mod tidy
  go.mod
  go.sum
Labels: lgtm, jira/valid-reference, approved

#10 CNTRLPLANE-355: Add samples for OSP provider and more documentation
  .github/PULL_REQUEST_TEMPLATE.md
  Makefile
  examples/AWS/README.md
  examples/AWS/velero-s3-bucket-policy.json
  examples/BareMetal/README.md
  examples/Openstack/02-dpa-osp.yaml
  examples/Openstack/03-backup-osp.yaml
  examples/Openstack/04-restore-osp.yaml
  examples/Openstack/README.md
  examples/README.md
Labels: lgtm, jira/valid-reference, approved

#13 NO-JIRA: Hermeto: go mod vendor
  vendor/modules.txt
Labels: lgtm, jira/valid-reference, approved

#12 NO-JIRA: Add Tiger to owners file for maintenance
  OWNERS
Labels: lgtm, jira/valid-reference, approved

#11 CNTRLPLANE-323: No pod restoration to avoid NodeSelector issues with podPlugin
  main.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/core/backup.go
  pkg/core/restore.go
  pkg/core/types/types.go
  pkg/core/validation/backup.go
  pkg/core/validation/restore.go
Labels: lgtm, jira/valid-reference, approved

#17 NO-JIRA: Hermeto: go mod vendor
  go.mod
  go.sum
  vendor/github.com/robfig/cron/v3/.gitignore
  vendor/github.com/robfig/cron/v3/.travis.yml
  vendor/github.com/robfig/cron/v3/LICENSE
  vendor/github.com/robfig/cron/v3/README.md
  vendor/github.com/robfig/cron/v3/chain.go
  vendor/github.com/robfig/cron/v3/constantdelay.go
  vendor/github.com/robfig/cron/v3/cron.go
  vendor/github.com/robfig/cron/v3/doc.go
  vendor/github.com/robfig/cron/v3/logger.go
  vendor/github.com/robfig/cron/v3/option.go
  vendor/github.com/robfig/cron/v3/parser.go
  vendor/github.com/robfig/cron/v3/spec.go
  vendor/modules.txt
Labels: tide/merge-method-squash, lgtm, jira/valid-reference, approved

#16 CNTRLPLANE-720: Add Goreleaser for automatically generate the multiarch binaries
  .gitignore
  .goreleaser.yaml
  Dockerfile
  Makefile
  pkg/version/version.go
  pkg/version/version_test.go
Labels: lgtm, jira/valid-reference, approved

#20 CNTRLPLANE-356: build arm64 and ppc
  .tekton/hypershift-oadp-plugin-main-pull-request.yaml
  .tekton/hypershift-oadp-plugin-main-push.yaml
Labels: lgtm, jira/valid-reference, approved

#23 CNTRLPLANE-356: build missing archs
  .tekton/hypershift-oadp-plugin-main-pull-request.yaml
  .tekton/hypershift-oadp-plugin-main-push.yaml
  .tekton/hypershift-oadp-plugin-oadp-1-5-pull-request.yaml
  .tekton/hypershift-oadp-plugin-oadp-1-5-push.yaml
Labels: lgtm, jira/valid-reference, approved

#31 CNTRLPLANE-356: Oadp 1.5 floating tag
  .tekton/hypershift-oadp-plugin-oadp-1-5-push.yaml
Labels: lgtm, jira/valid-reference, approved

#18 CNTRLPLANE-362: HCP-OADP Plugin: Add support for Kubevirt Platform
  examples/kubevirt/02-dpa-kubevirt.yaml
  examples/kubevirt/03-backup-kubevirt.yaml
  examples/kubevirt/04-restore-kubevirt.yaml
  examples/kubevirt/README.md
  pkg/common/types.go
  pkg/core/backup.go
  pkg/core/types/types.go
Labels: lgtm, jira/valid-reference, approved

#40 OCPBUGS-55469: Removed hardcoded namespace in favor of backup.Namespace
  pkg/common/utils.go
Labels: jira/valid-bug, lgtm, jira/valid-reference, jira/severity-important, approved

#42 feat(tekton): add latest floating tag
  .tekton/hypershift-oadp-plugin-main-push.yaml
Labels: lgtm, approved
