Repository openshift/hypershift-oadp-plugin, pull requests merged in 2025-08, with the labels that each got.

#95 OADP-6248: use the namespace where the plugin runs to get find backups
  pkg/core/restore.go
Labels: lgtm, jira/valid-reference, approved

#96 OADP-6248: fix restore after consult
  pkg/core/restore.go
Labels: lgtm, jira/valid-reference, approved

#94 OCPBUGS-58410,OCPBUGS-59881,OCPBUGS-60256: Improve backup resource filtering and race condition handling
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/core/backup.go
  pkg/core/validation/backup.go
  pkg/core/validation/backup_test.go
Labels: jira/valid-bug, lgtm, jira/valid-reference, approved, jira/severity-critical

#102 Update oadp-1.4 branch to oadp-1.5
  README.md
  docs/references/DataMover/DataMover-implementation.md
  go.mod
  go.sum
  pkg/common/scheme.go
  pkg/common/types.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/core/backup.go
  pkg/core/restore.go
  pkg/core/types/types.go
  pkg/core/validation/backup.go
  pkg/core/validation/backup_test.go
  pkg/core/validation/restore.go
  pkg/platform/aws/aws.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#105 Konflux: rename oadp-1.4 .tekton/ files
  .tekton/oadp-hypershift-oadp-plugin-oadp-1-4-pull-request.yaml
  .tekton/oadp-hypershift-oadp-plugin-oadp-1-4-push.yaml
Labels: lgtm, approved
