Repository openshift/hypershift-oadp-plugin, pull requests merged in 2025-05, with the labels that each got.

#48 OADP-6121: Return early when plugin enabled but not HC involved
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/core/backup.go
Labels: lgtm, jira/valid-reference, approved

#49 OADP-6121: Return early when plugin enabled but not HC involved
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/core/backup.go
Labels: lgtm, jira/valid-reference, approved

#55 remove busybox, update to conform with other plugins
  Dockerfile
Labels: lgtm, approved

#57 OADP-6147: break out if restore is not HCP
  pkg/common/utils.go
  pkg/core/restore.go
Labels: lgtm, jira/valid-reference, approved

#56 fix Dockerfile to match oadp plugins
  Dockerfile
Labels: lgtm, approved

#60 OCPBUGS-56430: Include RestoredFromBackup annotation on HostedCluster during restoration
  pkg/common/types.go
  pkg/core/backup.go
  pkg/core/restore.go
Labels: jira/valid-bug, lgtm, jira/valid-reference, approved
